// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0SaQpocN6hiEYONXERPaFXj0F9CHBU-c',
    appId: '1:788557808094:web:64966e3f13733ef5011d4f',
    messagingSenderId: '788557808094',
    projectId: 'softeng-egghunt',
    authDomain: 'softeng-egghunt.firebaseapp.com',
    storageBucket: 'softeng-egghunt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCY_T-yhKtxkpNVcq8xxRqZHD_0dO2jj4',
    appId: '1:788557808094:android:8096a129711832d9011d4f',
    messagingSenderId: '788557808094',
    projectId: 'softeng-egghunt',
    storageBucket: 'softeng-egghunt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_RfvJ0UTfWKPNfUBo02rT_jwr8pzdo-E',
    appId: '1:788557808094:ios:126dcc8bf5679017011d4f',
    messagingSenderId: '788557808094',
    projectId: 'softeng-egghunt',
    storageBucket: 'softeng-egghunt.appspot.com',
    iosBundleId: 'com.octo.softeng.egghunt.admin.softengEgghuntAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_RfvJ0UTfWKPNfUBo02rT_jwr8pzdo-E',
    appId: '1:788557808094:ios:d05768926fd58b7a011d4f',
    messagingSenderId: '788557808094',
    projectId: 'softeng-egghunt',
    storageBucket: 'softeng-egghunt.appspot.com',
    iosBundleId: 'com.octo.softeng.egghunt.admin.softengEgghuntAdmin.RunnerTests',
  );
}
